force-app/main/default/objects/Helpdesk_Ticket__c/Helpdesk_Ticket__c.object-meta.xml
<CustomObject>
    <label>Helpdesk Ticket</label>
    <nameField>
        <displayFormat>TIC={0000}</displayFormat>
        <label>Helpdesk Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Helpdesk Ticket</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Helpdesk_Ticket__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Helpdesk_Ticket__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Helpdesk_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HelpdeskTicketTriggerHandler.cls
public class HelpdeskTicketTriggerHandler {
    public static void setPriorityOnInsert(List<Helpdesk_Ticket__c> newTickets){
        for(Helpdesk_Ticket__c rec : newtickets){
            Switch on rec.Category__c{
                when 'Access'{
                    rec.Priority__c = 'High';
                }
                when 'Hardware'{
                    rec.Priority__c ='High';
                }
                when 'Software'{
                    rec.Priority__c = 'Medium';
                }
                when 'Other'{
                    rec.Priority__c = 'Low';
                }
                when else {
                    throw new InvalidCategoryException('Category ='+rec.Category__c+' is not a valid value. Ticket userId ='+rec.Employee__c);
                }
            }
            
        }
    }
    
    public class InvalidCategoryException extends Exception {}

}