force-app/main/default/objects/Helpdesk_Ticket__c/Helpdesk_Ticket__c.object-meta.xml
<CustomObject>
    <label>Helpdesk Ticket</label>
    <nameField>
        <displayFormat>TIC={0000}</displayFormat>
        <label>Helpdesk Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Helpdesk Ticket</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Helpdesk_Ticket__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Helpdesk_Ticket__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Helpdesk_Ticket</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HelpdeskTicketService.cls
public class HelpdeskTicketService {
    @InvocableMethod(Label='create' description='Action method to create ticket')
    public static list<OuterWrapper> createTicket(List<InsertWrapper> requests){
        List<Helpdesk_Ticket__c> htList = new list<Helpdesk_Ticket__c>();
        for(InsertWrapper iw: requests){
            Helpdesk_Ticket__c ht = new Helpdesk_Ticket__c();
            ht.Subject__c = iw.Subject;
            ht.Category__c = iw.Category;
            ht.Description__c = iw.description;
             ht.Employee__c = UserInfo.getUserId();
            htList.add(ht);
        }
        if(!htList.isEmpty()){
            insert htList;
        }
        List<OuterWrapper> results = new list<OuterWrapper>();
        for(Helpdesk_Ticket__c ht : htList){
            OuterWrapper Ow = new OuterWrapper();
            Ow.Name =ht.Name;
            Ow.Id= ht.Id;
            results.add(Ow);
        }
        return results;
    }
    
    public class InsertWrapper{
       	 @InvocableVariable
        public String Subject; 
         @InvocableVariable
        public String Description;
         @InvocableVariable
        public String Category;
        
    }
    
     public class OuterWrapper{
        @InvocableVariable
        public String Name; 
        @InvocableVariable
        public String Id;
        
    }
    

}